### ISSUE TITLE
Need usage example in README.md

### ISSUE THREAD

**Issue by DrSensor** [hack2root/build#1]
How to use this library?

**Comment by hack2root** [comment]
Currently, you can find some use cases in tests, i will add major use cases in wiki.

There are files under [UnitTestProject](https://github.com/hack2root/build/tree/master/UnitTestProject) folder.

Each TestSetxxx.cs corresponds to related tests in UnitTestxxx.cs

**Comment by hack2root** [comment]
https://github.com/hack2root/build/commit/263ab53a389294dba9c3008800c83acd523c408e
